workflows:
  maui-release:
    name: Build iOS + Windows .NET MAUI App
    environment:
      vars:
        DOTNET_VERSION: "9.0.306"  # укажи свою точную версию SDK
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
      xcode: latest
      os: macos-13.0  # для iOS сборки
    scripts:
      - name: Install .NET, Restore, Build iOS and Windows
        script: |
          echo "=== Installing .NET SDK $DOTNET_VERSION ==="
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --version $DOTNET_VERSION
          export DOTNET_ROOT=$HOME/.dotnet
          export PATH=$DOTNET_ROOT:$PATH
          dotnet --version

          echo "=== Restoring NuGet packages for iOS ==="
          dotnet restore DictionaryApp/DictionaryApp.csproj

          echo "=== Building iOS .NET MAUI App ==="
          dotnet publish DictionaryApp/DictionaryApp.csproj \
            -c Release -f net9.0-ios \
            /p:ArchiveOnBuild=true \
            /p:BuildIpa=true

          echo "=== Building Windows .NET MAUI App ==="
          dotnet publish DictionaryApp/DictionaryApp.csproj \
            -c Release -f net9.0-windows10.0.22621.0 \
            -p:Platform=x64

    artifacts:
      # iOS
      - "DictionaryApp/bin/Release/net9.0-ios/ios-arm64/publish/*.ipa"
      # Windows
      - "DictionaryApp/bin/Release/net9.0-windows10.0.22621.0/win-x64/publish/**/*"

    publishing:
      email:
        recipients:
          - your-email@example.com
