workflows:
  ios-release:
    name: Build iOS .NET MAUI App
    environment:
      vars:
        DOTNET_VERSION: "9.0.306"
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
      xcode: latest
    scripts:
      - name: Install .NET SDK and Restore/Build iOS
        script: |
          echo "=== Installing .NET SDK $DOTNET_VERSION ==="
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --version $DOTNET_VERSION
          export DOTNET_ROOT=$HOME/.dotnet
          export PATH=$DOTNET_ROOT:$PATH
          dotnet --version

          echo "=== Installing MAUI iOS workload ==="
          dotnet workload install maui-ios

          echo "=== Restoring NuGet packages ==="
          dotnet restore DictionaryApp/DictionaryApp.csproj

          echo "=== Building iOS .NET MAUI App ==="
          dotnet publish DictionaryApp/DictionaryApp.csproj \
            -c Release -f net9.0-ios \
            /p:ArchiveOnBuild=true \
            /p:BuildIpa=true

    artifacts:
      - "DictionaryApp/bin/Release/net9.0-ios/ios-arm64/publish/*.ipa"
